name: cheaters_update

on:
  schedule:
    - cron:  '*/20 * * * *'

# test
#   push:
#     branches: master
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cheaters_update
      run: |
        bash ./.github/cheaters_update.sh
        bash ./.github/git_push.sh

